/*
 * This source file was generated by the Gradle 'init' task
 */
package oosd;

import oosd.model.Game;
import oosd.model.GameDifficulty;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Game game = new Game(GameDifficulty.MEDIUM);
    }
}
